### ISSUE TITLE
Rendering.proto is Under-defined

### ISSUE THREAD

**Issue by bugerry87** [restorecommerce/libs#122]
The rendering message type is very much under-defined.
It declares `Any` where a certain known structure is requested such as for `templates` i.e.:

```json
{
  [template_name]: {
    "body": (Buffer | String),
    "layout": (Buffer | String),
  }
}
```

Instead there should be a dedicated repeated message to describe these templates such as:

```yaml
message Template {
  name: string = 1;
  ordinal: uint32 = 2; // sort number - just in case if the list order can't be preserved, but should
  body: string = 3; // or Buffer - however then we should also provide a charset coding!
  layout: string = 4; // or Buffer
  style_url: string = 5; // Why is style (css) just a URL while the others payload data?
}
``` 

Furthermore, the response is no more than an `Any` with `id` while in case of an error the keyword `error` shares the same layer as the render results! Errors and render results should be separated, rather use `Status` and/or `OperationStatus` like all the other services.

packages/protos/io/restorecommerce/rendering.proto

```
message Payload {
  // json with <key, template> pairs
  // e.g. { 'subject': ..., 'message':....}
  optional google.protobuf.Any templates = 1;
  optional google.protobuf.Any data = 2;  // data to fill template with
  optional string style_url = 3; // stylesheet URL

  enum Strategy { // style-applying 'strategy'
    INLINE = 0;
    COPY = 1;
  }
  optional Strategy strategy = 4;  // inlining, copying CSS into <style>, etc...
  // rendering options JSON object
  optional google.protobuf.Any options = 5;
  // content type for rendering such as 'application/html' or 'application/text'
  optional string content_type = 6;
}

message RenderResponse {
  optional string id = 1;
  repeated google.protobuf.Any responses = 2;  // error or HTML contents
}
```
